### ISSUE TITLE
trace seconds field is not effect

### ISSUE THREAD

**Issue by thinkAfCod** [felixge/fgtrace#3]
Below is my code using the fgtrace:
```
go func() {
    http.DefaultServeMux.Handle("/debug/fgprof", fgprof.Handler())
    http.DefaultServeMux.Handle("/debug/fgtrace", fgtrace.Config{})
    logger.Error("pprof server error", "err", http.ListenAndServe("0.0.0.0:1234", nil))
}()
```

curl get fgtrace file, I specified a trace time of 120s :
```
curl -o fgtrace.json http://localhost:1234/debug/fgtrace?seconds=120
```
but it returned the file immediately.So, Is there any configuration I need to modify?

**Comment by felixge** [comment]
Confirmed this is a bug. I screwed up some stuff while refactoring 🤦. Will fix.

**Comment by felixge** [comment]
Fixed by https://github.com/felixge/fgtrace/commit/f46702d4cf91a639e28ff95fec1462783665c1d1 - will cut a new release now. Sorry about this.
